title: Yujuan DING
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://JoanDING.JoanDING.github.io

aux_links:
  Template Repository: https://github.com/JoanDING/JoanDING.github.io
